name: Push to DB Branch

on:
  push:
    branches:
      - main  # 当推送到 main 分支时触发

jobs:
  push-to-db:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository (main branch)
        uses: actions/checkout@v4
        with:
          ref: main  # 检出 main 分支

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # - name: Install Dependencies
      #   run: |
      #     python -m pip install --upgrade pip
      #     pip install -r requirements.txt

      - name: Run Script
        run: python script.py

      - name: Check Result File
        run: |
          if [ ! -f result.txt ]; then
            echo "Error: result.txt does not exist."
            exit 1
          fi

      - name: Checkout DB Branch
        uses: actions/checkout@v4
        with:
          ref: db  # 检出 db 分支
          token: ${{ secrets.GITHUB_TOKEN }}  # 使用 GitHub Token

      - name: Ensure DB Directory Exists
        run: mkdir -p db

      - name: Copy Result to DB Branch
        run: |
          cp result.txt db/result.txt

      - name: Commit and Push Results
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add db/result.txt
          git commit -m "Update result.txt from main branch" || echo "No changes to commit"
          git push origin db