name: Push to DB Branch

on:
  push:
    branches:
      - main

jobs:
  push-to-db:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # - name: Install Dependencies
      #   run: |
      #     python -m pip install --upgrade pip
      #     pip install -r requirements.txt

      - name: Run Script
        run: python script.py

      - name: Check Files
        run: ls -la

      - name: Ensure DB Directory Exists
        run: mkdir -p db

      - name: Copy Result to DB Branch
        run: |
          cp result.txt db/result.txt

      - name: Checkout DB Branch
        uses: actions/checkout@v4
        with:
          ref: db
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Copy Result to DB Branch (again)
        run: |
          cp ${{ github.workspace }}/db/result.txt ${{ github.workspace }}/result.txt

      - name: Commit and Push Results
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add result.txt
          git commit -m "Update result.txt from main branch" || echo "No changes to commit"
          git push origin db