name: Push to DB Branch

on:
  push:
    branches:
      - main  # 当推送到 main 分支时触发

jobs:
  push-to-db:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository (main branch)
        uses: actions/checkout@v4
        with:
          ref: main  # 检出 main 分支

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'


      - name: Run Script
        run: python script.py

      - name: Check Result File
        run: |
          if [ ! -f result.txt ]; then
            echo "Error: result.txt does not exist."
            exit 1
          fi

      - name: Publish result.txt to db branch
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: db
          FOLDER: .
          COMMIT_NAME: github-actions[bot]
          COMMIT_EMAIL: github-actions[bot]@users.noreply.github.com
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}